apiVersion: v1
kind: Namespace
metadata:
  name: traefik-redirect-manager
---
# CRD for redirect routes
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redirectroute.traefik-redirect-manager.palojarvi.fi
  namespace: traefik-redirect-manager
spec:
  group: traefik-redirect-manager.palojarvi.fi
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                source: 
                  type: string
                target: 
                  type: string
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
  scope: Namespaced
  names:
    plural: redirectroutes
    singular: redirectroute
    kind: RedirectRoute
---
# RBAC service account

---
# RBAC role

---
# RBAC role binding

---
# Deployment
